## NumPy
Numerical Python

In [1]:
import numpy as np

In [4]:
an_array = np.arange(10) # arange = array range which creates a vector of specified length

In [3]:
an_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### ndarray

In [5]:
nd_array = np.random.randn(2, 3)

In [6]:
nd_array

array([[-1.26113136, -0.3725262 , -0.51558152],
       [-1.29197474, -0.62373855, -0.94962939]])

In [7]:
nd_array * 10

array([[-12.61131355,  -3.72526197,  -5.15581518],
       [-12.91974739,  -6.23738555,  -9.49629388]])

In [8]:
nd_array + nd_array

array([[-2.52226271, -0.74505239, -1.03116304],
       [-2.58394948, -1.24747711, -1.89925878]])

In [9]:
nd_array.shape # gives the size of the array

(2, 3)

In [10]:
nd_array.dtype # gives the type of the elements in the homogeneous array

dtype('float64')

In [11]:
a_list = range(5)

In [12]:
an_array = np.array(a_list)

In [13]:
an_array

array([0, 1, 2, 3, 4])

Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array.

In [14]:
b_list = [range(4), range(5,9)]

In [15]:
b_array = np.array(b_list)
b_array

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [16]:
b_array.ndim


2

In [17]:
b_array.shape

(2, 4)

In [18]:
b_array.dtype

dtype('int64')

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.empty((2,3,3))

array([[[ 1.28822975e-231, -4.33276241e-311,  4.44659081e-323],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 1.28822975e-231,  1.28822975e-231,  2.96439388e-323]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 1.28822975e-231,  1.28822975e-231,  1.48219694e-323],
        [ 2.41907520e-312,  1.28822975e-231,  1.25593681e-308]]])

In [25]:
np.arange(4)

array([0, 1, 2, 3])

In [29]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Converting the dtype of an ndarray.

In [30]:
an_array.dtype

dtype('int64')

In [31]:
an_array.astype(np.float64)

array([0., 1., 2., 3., 4.])

In [32]:
an_array.dtype

dtype('int64')

Converting numbers in strings to numeric form. 

In [34]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

Square root of all elements in an array.

In [35]:
an_array ** 0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])